-- Criar tabelas PCA separadas por ano (2022-2024)
-- Execute diretamente no phpMyAdmin

-- PCA 2022
CREATE TABLE `pca_2022` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `numero_contratacao` varchar(50) DEFAULT NULL,
  `status_contratacao` varchar(100) DEFAULT NULL,
  `situacao_execucao` varchar(100) DEFAULT 'Não iniciado',
  `titulo_contratacao` varchar(500) DEFAULT NULL,
  `categoria_contratacao` varchar(200) DEFAULT NULL,
  `uasg_atual` varchar(100) DEFAULT NULL,
  `valor_total_contratacao` decimal(15,2) DEFAULT NULL,
  `data_inicio_processo` date DEFAULT NULL,
  `data_conclusao_processo` date DEFAULT NULL,
  `prazo_duracao_dias` int(11) DEFAULT NULL,
  `area_requisitante` varchar(200) DEFAULT NULL,
  `numero_dfd` varchar(50) DEFAULT NULL,
  `prioridade` varchar(50) DEFAULT NULL,
  `numero_item_dfd` varchar(50) DEFAULT NULL,
  `data_conclusao_dfd` date DEFAULT NULL,
  `classificacao_contratacao` varchar(200) DEFAULT NULL,
  `codigo_classe_grupo` varchar(50) DEFAULT NULL,
  `nome_classe_grupo` varchar(200) DEFAULT NULL,
  `codigo_pdm_material` varchar(50) DEFAULT NULL,
  `nome_pdm_material` varchar(200) DEFAULT NULL,
  `codigo_material_servico` varchar(100) DEFAULT NULL,
  `descricao_material_servico` varchar(1000) DEFAULT NULL,
  `unidade_fornecimento` varchar(50) DEFAULT NULL,
  `valor_unitario` decimal(15,2) DEFAULT NULL,
  `quantidade` int(11) DEFAULT NULL,
  `valor_total` decimal(15,2) DEFAULT NULL,
  `criado_em` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_numero_contratacao` (`numero_contratacao`),
  KEY `idx_area_requisitante` (`area_requisitante`),
  KEY `idx_numero_dfd` (`numero_dfd`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- PCA 2023
CREATE TABLE `pca_2023` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `numero_contratacao` varchar(50) DEFAULT NULL,
  `status_contratacao` varchar(100) DEFAULT NULL,
  `situacao_execucao` varchar(100) DEFAULT 'Não iniciado',
  `titulo_contratacao` varchar(500) DEFAULT NULL,
  `categoria_contratacao` varchar(200) DEFAULT NULL,
  `uasg_atual` varchar(100) DEFAULT NULL,
  `valor_total_contratacao` decimal(15,2) DEFAULT NULL,
  `data_inicio_processo` date DEFAULT NULL,
  `data_conclusao_processo` date DEFAULT NULL,
  `prazo_duracao_dias` int(11) DEFAULT NULL,
  `area_requisitante` varchar(200) DEFAULT NULL,
  `numero_dfd` varchar(50) DEFAULT NULL,
  `prioridade` varchar(50) DEFAULT NULL,
  `numero_item_dfd` varchar(50) DEFAULT NULL,
  `data_conclusao_dfd` date DEFAULT NULL,
  `classificacao_contratacao` varchar(200) DEFAULT NULL,
  `codigo_classe_grupo` varchar(50) DEFAULT NULL,
  `nome_classe_grupo` varchar(200) DEFAULT NULL,
  `codigo_pdm_material` varchar(50) DEFAULT NULL,
  `nome_pdm_material` varchar(200) DEFAULT NULL,
  `codigo_material_servico` varchar(100) DEFAULT NULL,
  `descricao_material_servico` varchar(1000) DEFAULT NULL,
  `unidade_fornecimento` varchar(50) DEFAULT NULL,
  `valor_unitario` decimal(15,2) DEFAULT NULL,
  `quantidade` int(11) DEFAULT NULL,
  `valor_total` decimal(15,2) DEFAULT NULL,
  `criado_em` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_numero_contratacao` (`numero_contratacao`),
  KEY `idx_area_requisitante` (`area_requisitante`),
  KEY `idx_numero_dfd` (`numero_dfd`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- PCA 2024
CREATE TABLE `pca_2024` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `numero_contratacao` varchar(50) DEFAULT NULL,
  `status_contratacao` varchar(100) DEFAULT NULL,
  `situacao_execucao` varchar(100) DEFAULT 'Não iniciado',
  `titulo_contratacao` varchar(500) DEFAULT NULL,
  `categoria_contratacao` varchar(200) DEFAULT NULL,
  `uasg_atual` varchar(100) DEFAULT NULL,
  `valor_total_contratacao` decimal(15,2) DEFAULT NULL,
  `data_inicio_processo` date DEFAULT NULL,
  `data_conclusao_processo` date DEFAULT NULL,
  `prazo_duracao_dias` int(11) DEFAULT NULL,
  `area_requisitante` varchar(200) DEFAULT NULL,
  `numero_dfd` varchar(50) DEFAULT NULL,
  `prioridade` varchar(50) DEFAULT NULL,
  `numero_item_dfd` varchar(50) DEFAULT NULL,
  `data_conclusao_dfd` date DEFAULT NULL,
  `classificacao_contratacao` varchar(200) DEFAULT NULL,
  `codigo_classe_grupo` varchar(50) DEFAULT NULL,
  `nome_classe_grupo` varchar(200) DEFAULT NULL,
  `codigo_pdm_material` varchar(50) DEFAULT NULL,
  `nome_pdm_material` varchar(200) DEFAULT NULL,
  `codigo_material_servico` varchar(100) DEFAULT NULL,
  `descricao_material_servico` varchar(1000) DEFAULT NULL,
  `unidade_fornecimento` varchar(50) DEFAULT NULL,
  `valor_unitario` decimal(15,2) DEFAULT NULL,
  `quantidade` int(11) DEFAULT NULL,
  `valor_total` decimal(15,2) DEFAULT NULL,
  `criado_em` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_numero_contratacao` (`numero_contratacao`),
  KEY `idx_area_requisitante` (`area_requisitante`),
  KEY `idx_numero_dfd` (`numero_dfd`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;